version: '3.8'

services:
  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - ticknet
    restart: always

  influxdb:
    image: influxdb
    container_name: influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=telegraf
      - INFLUXDB_ADMIN_PASSWORD=telegrafpassword
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=telegrafpassword
    volumes:
      - ./influxdb:/var/lib/influxdb
    networks:
      - ticknet
    ports:
      - "8086:8086"
    restart: always

  chronograf:
    image: chronograf
    container_name: chronograf
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USER=telegraf
      - INFLUXDB_PASSWORD=telegrafpassword
    ports:
      - "8888:8888"
    networks:
      - ticknet
    restart: always

  kapacitor:
    image: kapacitor
    container_name: kapacitor
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
      - KAPACITOR_INFLUXDB_0_USERNAME=telegraf
      - KAPACITOR_INFLUXDB_0_PASSWORD=telegrafpassword
      - KAPACITOR_INFLUXDB_0_DATABASE=self
    volumes:
      - ./kapacitor:/var/lib/kapacitor
    networks:
      - ticknet
    restart: always

networks:
  ticknet:
    driver: bridge
